const fs = require('fs');
let file = 'project/src/components/ReceptionistServiceHub.tsx';
let content = fs.readFileSync(file, 'utf8');

const replacements = {
  'Cổng Phục Vụ Khách Hàng & Dịch Vụ Lễ Tân (Receptionist Service Hub)': 'Receptionist Service Hub',
  'Điều Hành Buồng Phòng & Gọi Món Trực Tiếp': 'Room Management & Direct Ordering',
  'Lễ tân dễ dàng theo dõi tình trạng buồng phòng thực tế, bấm hối dọn gấp khi khách đến sớm hoặc gọi đồ ăn/thức uống/tiện ích lên phòng ghi nợ trực tiếp vào Booking.': "Easily monitor real-time room status, request urgent cleaning, or order F&B directly to the guest's bill.",
  'Sơ Đồ Phòng & Phục Vụ': 'Rooms & Services',
  'Đơn Dịch Vụ Đang Xử Lý': 'Pending Orders',
  'Dịch Vụ Thuê Xe Tự Lái': 'Self-Driving Car Rentals',
  'Dịch Vụ Thuê Xe': 'Car Rentals',
  'Giám Sát Trải Nghiệm': 'Experiences Dashboard',
  'Làm mới': 'Refresh',
  'Lọc theo Tầng:': 'Filter by Floor:',
  'Tất cả (': 'All (',
  'Tầng': 'Floor',
  'Chú thích:': 'Legend:',
  'Trống (Có thể bán)': 'Available (Ready)',
  'Đang có khách ở': 'In Use',
  'Cần dọn dẹp': 'Dirty (Needs Cleaning)',
  'Đang bảo trì': 'Maintenance',
  'Phòng ': 'Room ',
  'Ghi chú lễ tân:': 'Receptionist notes:',
  'Khách vừa trả phòng lúc 12:00': 'Guest just checked out at 12:00',
  'Khách VIP: Trần Đức Đạt (Check-out mai)': 'VIP Guest: Trần Đức Đạt (Check-out tomorrow)',
  'Khách gia đình: Lê Thị Mai': 'Family Guest: Lê Thị Mai',
  'Đang sửa chữa vòi nước nhà tắm': 'Repairing bathroom faucet',
  'Phở Bò Kobe Đặc Biệt': 'Special Kobe Beef Pho',
  'Nước Cam Tươi Nguyên Chất': 'Fresh Orange Juice',
  'Cà Phê Trứng Hà Nội': 'Hanoi Egg Coffee',
  'Giặt Ứi Nhanh (Set 3 đồ)': 'Express Laundry (3 items)',
  'Set Khăn Bông VIP Thêm': 'Extra VIP Towel Set',
  'Nước dùng hầm 24h thơm ngon': '24h simmered broth',
  'Cam tươi 100% không đường hóa học': '100% fresh orange, no sugar',
  'Thơm béo ngậy truyền thống': 'Traditional rich flavor',
  'Sấy thơm trả trong 3 giờ': 'Express 3h return',
  'Khăn cotton 100% cao cấp': '100% premium cotton',
  'Giao lên phòng P201 cho anh Đạt': 'Deliver to room P201 for Mr. Dat',
  'Khách phòng': 'Guest in room',
  'yêu cầu': 'requested',
  'Gọi Món F&B & Dịch Vụ Cho Phòng': 'Order F&B & Services for Room',
  'Khách VIP đang lưu trú': 'VIP guest staying',
  'Chi phí sẽ được tự động cộng vào hóa đơn Check-out.': 'Charges will be automatically added to the checkout bill.',
  'Tất cả': 'All',
  'ĐỒ ĂN': 'FOOD',
  'THỨC UỐNG': 'BEVERAGE',
  'GIẶT ỦI': 'LAUNDRY',
  'TIỆN ÍCH': 'AMENITY',
  'KHÁC': 'OTHER',
  'Ghi chú cho nhà bếp / nhân viên (VD: ít cay, không hành...):': 'Notes for kitchen / staff (e.g., less spicy, no onions...):',
  'Hủy Bỏ': 'Cancel',
  'Xác Nhận Gọi Món': 'Confirm Order',
  'đ': 'VND',
  'Đang phục vụ / Chờ xử lý': 'Serving / Pending',
  'Chưa có đơn dịch vụ nào đang chờ xử lý.': 'No pending service orders.',
  'Mã Đơn:': 'Order ID:',
  'Phòng:': 'Room:',
  'Ghi lúc:': 'Ordered at:',
  'Từ chối / Hủy đơn': 'Reject / Cancel order',
  'Duyệt & Chuyển Xuống Nhà Bếp': 'Approve & Forward to Kitchen',
  'Đã chuyển bếp': 'Forwarded to kitchen',
  'Danh Sách Yêu Cầu Thuê Xe': 'Car Rental Requests',
  'Chưa có yêu cầu thuê xe nào được gửi lên.': 'No car rental requests submitted yet.',
  'Khách Hàng:': 'Guest:',
  'CCCD/GPLX:': 'ID/License:',
  'Chưa cung cấp': 'Not provided',
  'Ngày nhận:': 'Pickup date:',
  'Ngày trả:': 'Return date:',
  'Đang chờ xác nhận': 'Waiting for confirmation',
  'Hợp lệ (Khớp thông tin)': 'Valid (Info matches)',
  'Lệch thông tin': 'Info mismatch',
  'Từ Chối (Sai Thông Tin)': 'Reject (Invalid Info)',
  'Xác Nhận & Giao Xe': 'Confirm & Handover',
  'Đã thanh toán & hoàn tất bàn giao': 'Paid & Handover complete',
  'Đã từ chối do lệch thông tin': 'Rejected due to info mismatch',
  'Giám Sát & Điều Hành Trải Nghiệm Khách Sạn': 'Hotel Experience Monitoring & Management',
  'Bảng theo dõi trạng thái đặt tour trải nghiệm (climbing, rowing, swimming, skiing) của tất cả các phòng lưu trú.': 'Dashboard for tracking experience tours (climbing, rowing, swimming, skiing) of all staying rooms.',
  'Số Phòng': 'Room Number',
  'Trạng Thái Phòng': 'Room Status',
  'Khách Đang Ở': 'Current Guest',
  'Tour Trải Nghiệm Đã Đặt': 'Booked Experiences',
  'Kênh Đặt': 'Booking Channel',
  'Thanh Toán': 'Payment',
  'Tổng Chi Phí': 'Total Cost',
  'Chưa đặt trải nghiệm': 'No experiences booked',
  'Tour Trải nghiệm': 'Experience Tour',
  'Tại quầy lễ tân': 'At Reception',
  'Đặt trực tuyến': 'Online Booking',
  'Đã thanh toán (Online)': 'Paid (Online)',
  'Đã thanh toán': 'Paid',
  'Ghi nợ phòng (Chờ thanh toán)': 'Charged to room (Pending payment)',
  'Mã Đặt Phòng:': 'Booking ID:',
  'Đang dọn dẹp': 'Cleaning in progress',
  'Hoàn Tất Dọn (Thành AVAILABLE)': 'Finish Cleaning (Mark AVAILABLE)'
};

for (const [key, value] of Object.entries(replacements)) {
  content = content.split(key).join(value);
}

fs.writeFileSync(file, content, 'utf8');
