const fs = require('fs');
let file = 'project/src/components/ReceptionistServiceHub.tsx';
let content = fs.readFileSync(file, 'utf8');

const replacements = {
  '"ROOMS" | "ORDERS" | "CAR_RENTALS" | "EXPERIENCES"': '"ROOMS" | "ORDERS" | "CAR_RENTALS" | "EXPERIENCES" | "CHECKOUTS"',
  'C?ng Ph?c V? Khách Hàng & D?ch V? L? Tân (Receptionist Service Hub)': 'Receptionist Service Hub',
  'Ði?u Hành Bu?ng Ph?ng & G?i Món Tr?c Ti?p': 'Room Management & Direct Ordering',
  'L? tân d? dàng theo d?i t?nh tr?ng bu?ng ph?ng th?c t?, b?m h?i d?n g?p khi khách ð?n s?m ho?c g?i ð? ãn/th?c u?ng/ti?n ích lên ph?ng ghi n? tr?c ti?p vào Booking.': 'Easily monitor real-time room status, request urgent cleaning, or order F&B directly to the guest\\'s bill.',
  'Sõ Ð? Ph?ng & Ph?c V?': 'Rooms & Services',
  'Ðõn D?ch V? Ðang X? L?': 'Pending Orders',
  'D?ch V? Thuê Xe T? Lái': 'Self-Driving Car Rentals',
  'D?ch V? Thuê Xe': 'Car Rentals',
  'Giám Sát Tr?i Nghi?m': 'Experiences Dashboard',
  'Làm m?i': 'Refresh',
  'L?c theo T?ng:': 'Filter by Floor:',
  'T?t c? (': 'All (',
  'T?ng': 'Floor',
  'Chú thích:': 'Legend:',
  'Tr?ng (Có th? bán)': 'Available (Ready)',
  'Ðang có khách ?': 'In Use',
  'C?n d?n d?p': 'Dirty (Needs Cleaning)',
  'Ðang b?o tr?': 'Maintenance',
  'Ph?ng ': 'Room ',
  'Ghi chú l? tân:': 'Receptionist notes:',
  'Khách v?a tr? ph?ng lúc 12:00': 'Guest just checked out at 12:00',
  'Khách VIP: Tr?n Ð?c Ð?t (Check-out mai)': 'VIP Guest: Tr?n Ð?c Ð?t (Check-out tomorrow)',
  'Khách gia ð?nh: Lê Th? Mai': 'Family Guest: Lê Th? Mai',
  'Ðang s?a ch?a v?i ný?c nhà t?m': 'Repairing bathroom faucet',
  'Ph? B? Kobe Ð?c Bi?t': 'Special Kobe Beef Pho',
  'Ný?c Cam Týõi Nguyên Ch?t': 'Fresh Orange Juice',
  'Cà Phê Tr?ng Hà N?i': 'Hanoi Egg Coffee',
  'Gi?t ?i Nhanh (Set 3 ð?)': 'Express Laundry (3 items)',
  'Set Khãn Bông VIP Thêm': 'Extra VIP Towel Set',
  'Ný?c dùng h?m 24h thõm ngon': '24h simmered broth',
  'Cam týõi 100% không ðý?ng hóa h?c': '100% fresh orange, no sugar',
  'Thõm béo ng?y truy?n th?ng': 'Traditional rich flavor',
  'S?y thõm tr? trong 3 gi?': 'Express 3h return',
  'Khãn cotton 100% cao c?p': '100% premium cotton',
  'Giao lên ph?ng P201 cho anh Ð?t': 'Deliver to room P201 for Mr. Ð?t',
  'Khách ph?ng': 'Guest in room',
  'yêu c?u': 'requested',
  'G?i Món F&B & D?ch V? Cho Ph?ng': 'Order F&B & Services for Room',
  'Khách VIP ðang lýu trú': 'VIP guest staying',
  'Chi phí s? ðý?c t? ð?ng c?ng vào hóa ðõn Check-out.': 'Charges will be automatically added to the checkout bill.',
  'T?t c?': 'All',
  'Ð? ÃN': 'FOOD',
  'TH?C U?NG': 'BEVERAGE',
  'GI?T ?I': 'LAUNDRY',
  'TI?N ÍCH': 'AMENITY',
  'KHÁC': 'OTHER',
  'Ghi chú cho nhà b?p / nhân viên (VD: ít cay, không hành...):': 'Notes for kitchen / staff (e.g., less spicy, no onions...):',
  'H?y B?': 'Cancel',
  'Xác Nh?n G?i Món': 'Confirm Order',
  'ð': 'VND',
  'Ðang ph?c v? / Ch? x? l?': 'Serving / Pending',
  'Chýa có ðõn d?ch v? nào ðang ch? x? l?.': 'No pending service orders.',
  'M? Ðõn:': 'Order ID:',
  'Ph?ng:': 'Room:',
  'Ghi lúc:': 'Ordered at:',
  'T? ch?i / H?y ðõn': 'Reject / Cancel order',
  'Duy?t & Chuy?n Xu?ng Nhà B?p': 'Approve & Forward to Kitchen',
  'Ð? chuy?n b?p': 'Forwarded to kitchen',
  'Danh Sách Yêu C?u Thuê Xe': 'Car Rental Requests',
  'Chýa có yêu c?u thuê xe nào ðý?c g?i lên.': 'No car rental requests submitted yet.',
  'Khách Hàng:': 'Guest:',
  'CCCD/GPLX:': 'ID/License:',
  'Chýa cung c?p': 'Not provided',
  'Ngày nh?n:': 'Pickup date:',
  'Ngày tr?:': 'Return date:',
  'Ðang ch? xác nh?n': 'Waiting for confirmation',
  'H?p l? (Kh?p thông tin)': 'Valid (Info matches)',
  'L?ch thông tin': 'Info mismatch',
  'T? Ch?i (Sai Thông Tin)': 'Reject (Invalid Info)',
  'Xác Nh?n & Giao Xe': 'Confirm & Handover',
  'Ð? thanh toán & hoàn t?t bàn giao': 'Paid & Handover complete',
  'Ð? t? ch?i do l?ch thông tin': 'Rejected due to info mismatch',
  'Giám Sát & Ði?u Hành Tr?i Nghi?m Khách S?n': 'Hotel Experience Monitoring & Management',
  'B?ng theo d?i tr?ng thái ð?t tour tr?i nghi?m (climbing, rowing, swimming, skiing) c?a t?t c? các ph?ng lýu trú.': 'Dashboard for tracking experience tours (climbing, rowing, swimming, skiing) of all staying rooms.',
  'S? Ph?ng': 'Room Number',
  'Tr?ng Thái Ph?ng': 'Room Status',
  'Khách Ðang ?': 'Current Guest',
  'Tour Tr?i Nghi?m Ð? Ð?t': 'Booked Experiences',
  'Kênh Ð?t': 'Booking Channel',
  'Thanh Toán': 'Payment',
  'T?ng Chi Phí': 'Total Cost',
  'Chýa ð?t tr?i nghi?m': 'No experiences booked',
  'Tour Tr?i nghi?m': 'Experience Tour',
  'T?i qu?y l? tân': 'At Reception',
  'Ð?t tr?c tuy?n': 'Online Booking',
  'Ð? thanh toán (Online)': 'Paid (Online)',
  'Ð? thanh toán': 'Paid',
  'Ghi n? ph?ng (Ch? thanh toán)': 'Charged to room (Pending payment)',
  'M? Ð?t Ph?ng:': 'Booking ID:',
  'Ðang d?n d?p': 'Cleaning in progress',
  'Hoàn T?t D?n (Thành AVAILABLE)': 'Finish Cleaning (Mark AVAILABLE)'
};

for (const [key, value] of Object.entries(replacements)) {
  content = content.split(key).join(value);
}

fs.writeFileSync(file, content, 'utf8');
