// src/contains/incident.ts

export const INCIDENT_TYPES = {
  DAMAGE: 'DAMAGE',
  MISSING_HOTEL_ITEM: 'MISSING_HOTEL_ITEM',
  GUEST_LOST_ITEM: 'GUEST_LOST_ITEM',
  FOUND_ITEM: 'FOUND_ITEM',
  MAINTENANCE: 'MAINTENANCE',
  COMPLAINT: 'COMPLAINT',
  OTHER: 'OTHER',
} as const;

export const INCIDENT_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

export const INCIDENT_STATUS = {
  REPORTED: 'REPORTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  CUSTOMER_NOTIFIED: 'CUSTOMER_NOTIFIED',
  APPROVED_CHARGE: 'APPROVED_CHARGE',
  ADDED_TO_INVOICE: 'ADDED_TO_INVOICE',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
} as const;

export const LOST_FOUND_STATUS = {
  FOUND: 'FOUND',
  STORED: 'STORED',
  CUSTOMER_NOTIFIED: 'CUSTOMER_NOTIFIED',
  CLAIMED: 'CLAIMED',
  RETURNED: 'RETURNED',
  CLOSED: 'CLOSED', // <--- THÊM DÒNG NÀY
  DISPOSED: 'DISPOSED',
  REPORTED: 'REPORTED',
  INVESTIGATING: 'INVESTIGATING',
  WAITING_CUSTOMER: 'WAITING_CUSTOMER',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
  ESCALATED: 'ESCALATED',
} as const;

// WORKFLOW: Quy định trạng thái tiếp theo hợp lệ (Chống chuyển status ngược)
export const INCIDENT_WORKFLOW: Record<string, string[]> = {
  // Cho DAMAGE và MISSING_HOTEL_ITEM
  [INCIDENT_STATUS.REPORTED]: [INCIDENT_STATUS.UNDER_REVIEW, INCIDENT_STATUS.CANCELLED],
  [INCIDENT_STATUS.UNDER_REVIEW]: [INCIDENT_STATUS.CUSTOMER_NOTIFIED, INCIDENT_STATUS.CANCELLED],
  [INCIDENT_STATUS.CUSTOMER_NOTIFIED]: [INCIDENT_STATUS.APPROVED_CHARGE, INCIDENT_STATUS.RESOLVED],
  [INCIDENT_STATUS.APPROVED_CHARGE]: [INCIDENT_STATUS.ADDED_TO_INVOICE],
  [INCIDENT_STATUS.ADDED_TO_INVOICE]: [INCIDENT_STATUS.RESOLVED],
  [INCIDENT_STATUS.RESOLVED]: [INCIDENT_STATUS.CLOSED],
  [INCIDENT_STATUS.CLOSED]: [],
  [INCIDENT_STATUS.CANCELLED]: [],
};

export const FOUND_ITEM_WORKFLOW: Record<string, string[]> = {
  [LOST_FOUND_STATUS.FOUND]: [LOST_FOUND_STATUS.STORED, LOST_FOUND_STATUS.DISPOSED],
  [LOST_FOUND_STATUS.STORED]: [LOST_FOUND_STATUS.CUSTOMER_NOTIFIED, LOST_FOUND_STATUS.DISPOSED],
  [LOST_FOUND_STATUS.CUSTOMER_NOTIFIED]: [LOST_FOUND_STATUS.CLAIMED],
  [LOST_FOUND_STATUS.CLAIMED]: [LOST_FOUND_STATUS.RETURNED],
  [LOST_FOUND_STATUS.RETURNED]: [LOST_FOUND_STATUS.CLOSED],
  [LOST_FOUND_STATUS.CLOSED]: [],
  [LOST_FOUND_STATUS.DISPOSED]: [],
};

export const GUEST_LOST_ITEM_WORKFLOW: Record<string, string[]> = {
  [LOST_FOUND_STATUS.REPORTED]: [LOST_FOUND_STATUS.INVESTIGATING],
  [LOST_FOUND_STATUS.INVESTIGATING]: [LOST_FOUND_STATUS.WAITING_CUSTOMER, LOST_FOUND_STATUS.RESOLVED, LOST_FOUND_STATUS.REJECTED, LOST_FOUND_STATUS.ESCALATED],
  [LOST_FOUND_STATUS.WAITING_CUSTOMER]: [LOST_FOUND_STATUS.RESOLVED],
  [LOST_FOUND_STATUS.RESOLVED]: [],
  [LOST_FOUND_STATUS.REJECTED]: [],
  [LOST_FOUND_STATUS.ESCALATED]: [LOST_FOUND_STATUS.RESOLVED],
};